/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analytics': RouteRecordInfo<'/analytics', '/analytics', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/reset-password': RouteRecordInfo<'/auth/reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/signin': RouteRecordInfo<'/auth/signin', '/auth/signin', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/forbidden': RouteRecordInfo<'/forbidden', '/forbidden', Record<never, never>, Record<never, never>>,
    '/form': RouteRecordInfo<'/form', '/form', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/housing-data': RouteRecordInfo<'/housing-data', '/housing-data', Record<never, never>, Record<never, never>>,
    '/housing-development-data': RouteRecordInfo<'/housing-development-data', '/housing-development-data', Record<never, never>, Record<never, never>>,
    '/housing-development-form': RouteRecordInfo<'/housing-development-form', '/housing-development-form', Record<never, never>, Record<never, never>>,
    '/infrastructure-data': RouteRecordInfo<'/infrastructure-data', '/infrastructure-data', Record<never, never>, Record<never, never>>,
    '/infrastructure-form': RouteRecordInfo<'/infrastructure-form', '/infrastructure-form', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/analytics.vue': {
      routes: '/analytics'
      views: never
    }
    'src/pages/auth/forgot-password.vue': {
      routes: '/auth/forgot-password'
      views: never
    }
    'src/pages/auth/reset-password.vue': {
      routes: '/auth/reset-password'
      views: never
    }
    'src/pages/auth/signin.vue': {
      routes: '/auth/signin'
      views: never
    }
    'src/pages/auth/signup.vue': {
      routes: '/auth/signup'
      views: never
    }
    'src/pages/forbidden.vue': {
      routes: '/forbidden'
      views: never
    }
    'src/pages/form.vue': {
      routes: '/form'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/housing-data.vue': {
      routes: '/housing-data'
      views: never
    }
    'src/pages/housing-development-data.vue': {
      routes: '/housing-development-data'
      views: never
    }
    'src/pages/housing-development-form.vue': {
      routes: '/housing-development-form'
      views: never
    }
    'src/pages/infrastructure-data.vue': {
      routes: '/infrastructure-data'
      views: never
    }
    'src/pages/infrastructure-form.vue': {
      routes: '/infrastructure-form'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/users.vue': {
      routes: '/users'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
